UAMS-Web/UAMSWP-Find-a-Doc

- assets/json/acf-json/group_uamswp_locations.json
- includes/_unused/class.fad-locations-mb.php
- includes/class.fad-locations-acf.php
- templates/single-locations.php
- templates/single-physicians.php
- Add fallback image to location card
> Add fallback image to location card

- templates/taxonomy-condition.php
- templates/taxonomy-treatment_procedure.php
https://uamsweb.atlassian.net/browse/FD20-122
I created this branch from Dev, as Master didn't have everything I needed.
> FD20-122 Wrap the physician card loop in the right structural div

- templates/archive-expertise.php
- templates/archive-taxonomy-conditions.php
- templates/archive-taxonomy-treatments.php
- templates/single-expertise.php
- templates/taxonomy-condition.php
- templates/taxonomy-treatment_procedure.php
https://uamsweb.atlassian.net/browse/FD20-161
Created from dev, not master.
> FD20-161 Match top section layout of AoE / conditions / treatments root pages to default template

- templates/archive-taxonomy-conditions.php
- templates/archive-taxonomy-treatments.php
https://uamsweb.atlassian.net/browse/FD20-161
Changed condition / treatment html structure, now that I actually know how those pages work.
> FD20-161 continued, Refining HTML

- templates/single-physicians.php
If only English, hide with sr-only. If one language, say "Language". If multiple, say "Languages".
https://uamsweb.atlassian.net/browse/FD20-151
> Display language(s) on profile

- templates/archive-taxonomy-conditions.php
- templates/archive-taxonomy-treatments.php
Adjusting structure
https://uamsweb.atlassian.net/browse/FD20-125
> FD20-125 Create conditions root page

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-132
> FD20-132 Adjust physician appointment block with logic regarding Portal option and appointment eligibility

- templates/archive-physicians.php
https://uamsweb.atlassian.net/browse/FD20-8
Adding alert to top of physician list
> FD20-8 Block for if this is an emergency

- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-32
> Add fallback after-hours info for locations that aren't 24/7

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-165
Also moved around publications
> FD20-165 Reformat how TRI profile link is displayed

- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-148
> FD20-148 add parking map to location page

- templates/single-physicians.php
- Change to physician_short_clinical_bio
> Fix for description

- templates/single-locations.php
> Merge class attributes

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-175
> Add Associations to physician profile

- includes/class.fad-functions.php
- Requires portal slug to be uams-mychart
> Default value for portal

- templates/archive-taxonomy-conditions.php
- templates/archive-taxonomy-treatments.php
https://uamsweb.atlassian.net/browse/FD20-125
> Show All fix

- assets/json/acf-json/group_uamswp_physicians.json
https://uamsweb.atlassian.net/browse/FD20-137
> Move pubmed to research

- assets/json/acf-json/group_uamswp_expertise.json
https://uamsweb.atlassian.net/browse/FD20-131
> Fix bi-directional for AoE to Conditions & Treatments

- templates/single-expertise.php
- templates/taxonomy-condition.php
- templates/taxonomy-treatment_procedure.php
https://uamsweb.atlassian.net/browse/FD20-155
> FD20-155 Add featured video field for AoE, Conditions, Treatments

- templates/blocks/appointment.php
- templates/loops/conditions-loop.php
- templates/loops/treatments-loop.php
- templates/single-expertise.php
- templates/single-locations.php
- templates/single-physicians.php
- templates/taxonomy-condition.php
- templates/taxonomy-treatment_procedure.php
https://uamsweb.atlassian.net/browse/FD20-180
It looks a lot worse than it is.
> FD20-180 clean up container classes and styles

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-181
> FD20-181 change physician's academic section layout on large viewports

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-143
> FD20-143 Display AoE list instead of service line

- templates/archive-physicians.php
- templates/fwp/physician-loop.php
- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-142
Adding why not note, separated from 0 stars, if no rating available
> FD20-142 hide ratings if there is no ratings or reviews

- templates/fwp/physician-loop.php
- templates/loops/physician-card.php
- templates/single-locations.php
- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-186
> FD20-186 width of retina images oversized on retina display

- templates/loops/physician-card.php
https://uamsweb.atlassian.net/browse/FD20-189
> FD20-189-Remove-service-line-from-physician-cards

- templates/loops/location-card.php
https://uamsweb.atlassian.net/browse/FD20-197
> FD20-197 Accessibility issues

- templates/archive-locations.php
- templates/loops/location-card.php
- templates/single-expertise.php
- templates/single-locations.php
- templates/single-physicians.php
- templates/taxonomy-condition.php
- templates/taxonomy-treatment_procedure.php
https://uamsweb.atlassian.net/browse/FD20-183
> FD20-183 add appointment phone number field to locations

- templates/fwp/physician-loop.php
https://uamsweb.atlassian.net/browse/FD20-208
> FD20-208 replace service line with clinical title in physician list

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-210
> FD20-210 view more reviews modal just loads barnes reviews

- templates/loops/expertise-card.php
- templates/loops/physician-card.php
https://uamsweb.atlassian.net/browse/FD20-216
> Fd20 216 multi line elements exceed bounds of card body in ie11

- templates/archive-expertise.php
- templates/archive-locations.php
- templates/archive-physicians.php
- templates/archive-taxonomy-conditions.php
- templates/archive-taxonomy-treatments.php
- templates/single-locations.php
- templates/single-physicians.php
- templates/taxonomy-condition.php
- templates/taxonomy-treatment_procedure.php
https://uamsweb.atlassian.net/browse/FD20-214
> Fd20-214 add genesis skip link destination on fa d pages

- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-37
> Move affiliation content to within the same section as About

- templates/archive-physicians.php
- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-222
> Set unique id for modal title and update aria-labelledby value

- assets/json/acf-json/group_uamswp_conditions.json
- assets/json/acf-json/group_uamswp_physicians.json
- assets/json/acf-json/group_uamswp_treatments.json
Physicians will need to "update" to force the sync
> Bi-directional sync for treatments & conditions with physicians

- includes/class.fad-helper-functions.php
Reflects hierarchy & places link to archive page in the breadcrumbs
> Add Areas of Expertise custom breadcrumb

- templates/single-expertise.php
- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-237
> Fd20 237 display child areas of expertise

- templates/single-expertise.php
https://uamsweb.atlassian.net/browse/FD20-237
> Fd20-237 display child areas of expertise

- templates/single-expertise.php
Don't do truncated content if no custom excerpt. Limit custom excerpt to 30 characters.
> Add limited excerpt if there is a custom excerpt

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-249
I've added classes to the <main> element if a value exists for certain fields in the provider profile.
I couldn't figure out the best method to do the same for fields within repeaters, so I left those as comments in the file.
> Add various has-* classes to main element if values exist

- assets/json/acf-json/group_uamswp_locations.json
- assets/json/acf-json/group_uamswp_physicians.json
https://uamsweb.atlassian.net/browse/FD20-248
> Adjust instructions to include minimum character recommendation

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-263
> Fd20-263 fix html validation errors on provider pages

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-249
Apparently, I forgot to commit this line in the initial push.
If there's a better place to put these attribute values than as classes on main.doctor-item, let me know.
> Fd20-249 add identifier for presence of provider profile data

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-278
> Fd20-278 adjust structure of provider research section

- templates/single-expertise.php
https://uamsweb.atlassian.net/browse/FD20-260
> FD20-260 Add appointment block to individual AoE

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-249
Expanded to include check for valid location
> FD20-249 Add a unique identifier to each provider profile section for siteimprove

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-281
> FD20-281 Adjust provider appointment block if only location is not published

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-302
> FD20-302 add attribute to provider page for service line value

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-303
> Fd20-303 add attribute to provider page for age of image in years

- assets/json/acf-json/group_uamswp_physicians.json
https://uamsweb.atlassian.net/browse/FD20-304
> FD20-304 require both academic appointment fields

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-308
> FD20-308 fallback meta description for providers

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-310
> FD20-310 remove view all locations button if only one location

- templates/single-expertise.php
- templates/single-locations.php
- templates/single-physicians.php
- templates/taxonomy-condition.php
- templates/taxonomy-treatment_procedure.php
Relates to https://uamsweb.atlassian.net/browse/UW20-120
> Set classes to match standard structure for video embeds

- templates/taxonomy-condition.php
- templates/taxonomy-treatment_procedure.php
https://uamsweb.atlassian.net/browse/FD20-316
> FD20-316 add a unique identifier to each condition/treatment profile section for siteimprove

- assets/js/uamswp-loadmore.js
> Fix JS Error

- assets/json/acf-json/group_uamswp_locations.json
- assets/json/acf-json/group_uamswp_locations_alert.json
- includes/class.fad-settings-pages.php
- templates/archive-expertise.php
- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-332
> FD20-332 ability to bulk add alerts to location pages

- templates/single-locations.php
Theme update comes with this.
https://github.com/UAMS-Web/uams-2020/pull/229
> Moving location carousel indicators below

- templates/fwp/location-list.php
- Rearrange some code.
- Add clinic number as appointment number if no appointment number is defined in location.
> FD20-261 improve main appointments page phone number list

- assets/json/acf-json/group_uamswp_locations.json
- templates/loops/location-card.php
- templates/single-locations.php
- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-338
> Fd20-338 location closures

- assets/json/acf-json/group_uamswp_locations.json
- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-340
> Fd20-340 expand functionality on location alerts

- assets/json/acf-json/group_uamswp_locations.json
- templates/single-locations.php
Small formatting/structure changes
> Fd20-339 modified hours for location

- assets/json/acf-json/group_uamswp_physicians.json
- includes/class.fad-custom-post.php
- templates/doximity-list.php
I created a new taxonomy, so make sure I did that correctly.
> Fd20-346 adjust doximity output for facility name

- assets/json/acf-json/group_uamswp_locations.json
- assets/json/acf-json/group_uamswp_locations_telemed.json
- templates/loops/location-card.php
- templates/single-locations.php
Adjusted some instructions here and there.
Though, the big thing here are ...
... adding Find-a-Doc Settings inputs for generic telemedicine info that is included in the location front end's telemed section.
... adjusting the alert on the location card for closure, adding modified hours to it, and adding a "more info" link.
> Fd20-343 telemedicine info on locations

- includes/class.fad-helper-functions.php
Genesis to SEOPress Breadcrumbs to match 2020 theme
- Disable Genesis Breadcrumbs
- Add SEOPress Breadcrumbs
> Breadcrumb fixes

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-354
> FD20-354 Update provider location card with new alert structure

- assets/json/acf-json/group_uamswp_locations.json
- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-356
> FD20-356 Add option for variable hours on locations

- assets/css/app.css
- assets/scss/_locations-item.scss
- templates/single-locations.php
Adjustments to subtitle structure
> FD20-305 Child locations

- templates/loops/location-card.php
- templates/single-locations.php
- templates/single-physicians.php
Doing the needful on location cards
> Fd20 305  child locations

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-357
> FD20-357 Adjust possessive provider short name

- templates/loops/location-card.php
https://uamsweb.atlassian.net/browse/FD20-366
> Use correct variable in location card modified hours alert

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-368
> Fd20-368 Simplify referral reference in appointment block

- assets/scss/_conditions-treatments.scss
https://uamsweb.atlassian.net/browse/FD20-369
> FD20-369 - Hover state of condition/treatment list goes white

- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-358
This overwritten change was missed because I had accidentally sent the commit directly to Dev back on June 1. So there was no PR to look for.
> FD20-358 Convert get_field to variables in location profile

- templates/archive-locations.php
> FD20-373 locations filters

- assets/scss/_ajaxsearchpro.scss
- assets/scss/app.scss
> Add styles for ajax search pro

- templates/single-condition.php
- templates/single-locations.php
- templates/single-physicians.php
- templates/single-treatment.php
Carried the change through to the other instances of conditions/treatments
> FD20-384 AoE page only displaying 10 conditions

- assets/scss/_ajaxsearchpro.scss
- assets/scss/app.scss
- includes/class.fad-functions.php
- includes/class.fad-fwp-functions.php
- templates/archive-locations.php
- templates/archive-physicians.php
I believe this is ready for the next release.
https://uamsweb.atlassian.net/browse/FD20-373
> FD20-373 Ability to filter locations on location archive

- templates/loops/location-card.php
https://uamsweb.atlassian.net/browse/FD20-376
> FD20-376 Add appointment phone numbers to location cards on provider profiles

- templates/loops/expertise-card.php
Ready to go
https://uamsweb.atlassian.net/browse/FD20-375
> Fd20-375 parent reference in child aoe card

- templates/loops/location-card.php
Ready to go
https://uamsweb.atlassian.net/browse/FD20-376
> Fd20-376 phone numbers on location cards

- assets/json/acf-json/group_uamswp_physicians.json
https://uamsweb.atlassian.net/browse/FD20-389
This has gotten overwritten twice. But _BY GOD_, we're going to make this happen this time.
> Fd20-389 make service line required

- templates/loops/location-card.php
https://uamsweb.atlassian.net/browse/FD20-396
> FD20-396 Make closure alert link unique

- templates/fwp/physician-loop.php
https://uamsweb.atlassian.net/browse/FD20-395
> FD20-395 No aria-label on Full Profile button

- templates/provider-image.php
- Remove search
- Remove skip links
- Remove breadcrumbs
- Remove JS
- Validate provider ID as numeric
> Fixes for Provider Image - Display image only

- assets/json/acf-json/group_uamswp_locations.json
https://uamsweb.atlassian.net/browse/FD20-400
> FD20-400 Make location address fields required

- assets/json/acf-json/group_uamswp_physicians.json
https://uamsweb.atlassian.net/browse/FD20-401
> Fd20-401 Change provider appointment fields to required choices

- templates/single-condition.php
- templates/single-treatment.php
https://uamsweb.atlassian.net/browse/FD20-403
> FD20-403 Clarify provider disclaimer related to conditions and treatments

- includes/class.fad-custom-post.php
Add conditions, treatments, & expertise as id list and comma seperated list
> Update physician rest API information

- templates/single-expertise.php
https://uamsweb.atlassian.net/browse/FD20-405
https://uamsweb.atlassian.net/browse/FD20-406
> FD20-405 and FD-406 Child aoe list

- assets/json/acf-json/group_uamswp_physicians.json
Ready for the next release.
https://uamsweb.atlassian.net/browse/FD20-399
> FD20-399 Correct typo in Clinical Focus field instructions

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-410
> FD20-410 Change Arkansas Children's main appointment line in appointment block

- assets/json/acf-json/group_uamswp_locations.json
- assets/json/acf-json/group_uamswp_physicians.json
- assets/json/acf-tables/table_uamswp_locations.json
- includes/class.fad-acf-functions.php
- includes/class.fad-custom-post.php
- templates/doximity-list.php
- templates/gmb-list-location.php
- templates/gmb-list-provider.php
- templates/loops/location-card.php
- templates/single-locations.php
- templates/single-physicians.php
- Updates to GMB table templates
- Changes to how we set address line 2+ in locations.
- Addition of Google My Business tab to locations
- Addition of wide provider image input with 16:9 aspect ratio validation
- Updates to Doximity table template
> Fd20-412 create table for gmb import

- templates/single-physicians.php
> FD20-410 Change ACH appointment phone number

- templates/fwp/physician-loop.php
> Fd20 421 draft locations displaying on provider archive

- assets/json/acf-json/group_uamswp_locations.json
- assets/json/acf-tables/table_uamswp_locations.json
- templates/gmb-list-location.php
> Fd20 412 create table for gmb import

- assets/json/acf-json/group_uamswp_locations.json
- assets/json/acf-tables/table_uamswp_locations.json
- includes/class.fad-custom-post.php
- templates/gmb-list-location.php
https://uamsweb.atlassian.net/browse/FD20-420
> Fd20 420 gmb category selectors

- templates/single-physicians.php
$excerpt was not passing data, so we add a new var named $schema_description
> Update schema description

- templates/blocks/appointment.php
- templates/loops/expertise-card.php
- templates/loops/location-card.php
- templates/loops/physician-card.php
- templates/single-condition.php
- templates/single-expertise.php
- templates/single-locations.php
- templates/single-physicians.php
- templates/single-treatment.php
https://uamsweb.atlassian.net/browse/FD20-426
> FD20-426 Add html attributes to elements for GTM event tracking - Condition/Treatment Profile

- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-425
> FD20-425 Location external links not displaying for child locations

- templates/blocks/clinical-trials.php
- templates/blocks/locations.php
- templates/blocks/providers.php
- templates/loops/expertise-card.php
- templates/loops/location-card.php
- templates/loops/physician-card.php
- templates/single-condition.php
- templates/single-locations.php
- templates/single-physicians.php
- templates/single-treatment.php
Tested on dev and ready to go at the next good opportunity
> Hot Fix - Fd20-426 GTM events for conditions treatments

- templates/single-physicians.php
> FD20-426 GTM events for conditions treatments

- assets/json/acf-json/group_uamswp_conditions_cpt.json
- assets/json/acf-json/group_uamswp_expertise.json
- assets/json/acf-json/group_uamswp_treatments_cpt.json
- templates/single-condition.php
- templates/single-expertise.php
- templates/single-treatment.php
https://uamsweb.atlassian.net/browse/FD20-429
> Fd20-429 Repeatable CTA Bar section on AoE, Treatment, Condition

- templates/single-condition.php
- templates/single-expertise.php
- templates/single-locations.php
- templates/single-physicians.php
- templates/single-treatment.php
https://uamsweb.atlassian.net/browse/FD20-432
> FD20 432 Jump Links

- templates/single-expertise.php
Fixed a bug and found some unused bit in the child aoe heading
> FD20-432 jump links

- assets/json/acf-json/group_uamswp_physicians.json
https://uamsweb.atlassian.net/browse/FD20-409
> Set location input as required

- assets/css/app.css
- templates/single-condition.php
- templates/single-treatment.php
https://uamsweb.atlassian.net/browse/FD20-436
> FD20-436 Add disclaimer description to location sections

- assets/json/acf-json/group_uamswp_locations.json
- assets/json/acf-json/group_uamswp_mychart_scheduling.json
- assets/scss/_mychart-EmbeddedWidget.scss
- assets/scss/_mychart-scheduling.scss
- assets/scss/app.scss
- includes/class.fad-acf-functions.php
- includes/class.fad-settings-pages.php
- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-437
Will need Gulp after merge
> FD20-437 add mychart scheduling section to locations

- assets/json/acf-json/group_uamswp_locations_afterhours.json
- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-438
> Fd20-438 update after hours message

- assets/json/acf-json/group_uamswp_mychart_scheduling.json
- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-444
> FD20-444 Add linksource attribute to MyChart scheduling iframe

- templates/loops/resource-card.php
Update some overlooked var names in the var name localization initiative.
Also update provider name vars for ExtraMostBestest Localization.
> Knowledge base

- assets/css/app.css
- templates/single-expertise.php
- uamswp-find-a-doc.php
Forgot to pull the $post var into the function when I switched how the $resource_more_value value was defined. This adds it.
> Hot fix - AOE's TRL function global $post var

- assets/scss/_ajax-filter.scss
- includes/class.fad-functions.php
Adjusting message for when AJAX filters have been pre-applied due to The Trench
> FD20-367 on page filter with ajax

- templates/loops/physician-card.php
Ready for next release.
https://uamsweb.atlassian.net/browse/FD20-518
> Fd20-518 degrees not displaying on provider cards

- assets/json/acf-json/group_uamswp_locations.json
- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-521
> FD20-521 Customize Text in MyChart Scheduling Section

- assets/css/app.css
- includes/class.fad-functions.php
- templates/single-locations.php
- uamswp-find-a-doc.php
https://uamsweb.atlassian.net/browse/FD20-526
> FD20-526 show typical hours during modified days

- templates/blocks/locations-phone.php
Bug fix. General information phone number in associated location references had appointment subtitle. Added more logic down there.
> FD20-442 & FD20-439 Location Appointment Phone Numbers

- templates/archive-clinical-resource.php
- templates/archive-condition.php
- templates/archive-expertise.php
- templates/archive-locations.php
- templates/archive-physicians.php
- templates/archive-taxonomy-conditions.php
- templates/archive-taxonomy-treatments.php
- templates/archive-treatments.php
- templates/single-clinical-resource.php
- templates/single-condition.php
- templates/single-expertise.php
- templates/single-locations.php
- templates/single-treatment.php
- templates/taxonomy-condition.php
- templates/taxonomy-treatment_procedure.php
https://uamsweb.atlassian.net/browse/FD20-1378
> [FD20-1378] Find-a-Doc Meta Values Pulling Individual Post Title

- assets/json/acf-json/group_uamswp_locations.json
- templates/single-locations.php
Ready for release
https://uamsweb.atlassian.net/browse/FD20-445
> [FD20-439] Location modified hours repeater requires row even when empty

- assets/css/app.css
- includes/class.fad-functions.php
- templates/single-physicians.php
- uamswp-find-a-doc.php
https://uamsweb.atlassian.net/browse/FD20-449
> [FD20-449] Fallback short description on providers uses wrong a vs. an

- assets/css/app.css
- includes/class.fad-functions.php
- templates/single-physicians.php
- uamswp-find-a-doc.php
https://uamsweb.atlassian.net/browse/FD20-517
> [FD20-517] Add has-ratings check class to provider profile

- templates/blocks/locations-phone.php
https://uamsweb.atlassian.net/browse/FD20-2330
> [FD20-2330] Undefined variable $location_appointment_phone_query

- templates/loops/resource-card.php
https://uamsweb.atlassian.net/browse/FD20-507
> [FD20-507] Adjust clinical resource link text based on resource type

- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-500
> [FD20-500] Add references to AoEs back to the top section of provider profiles

- templates/blocks/clinical-resources.php
- templates/loops/resource-card.php
https://uamsweb.atlassian.net/browse/FD20-1534
* Adjusted HTML structure to match new structure for Stacked Image & Text
* Brought card image method in line with Stacked Image & Text
* Added alt and role attributes to archive fallback image
> [FD20-1534] Rebuild Stacked Image & Text and News Syndication Card Layout

- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-440
Ready for next release.
> [FD20-440] Add secondary button for location parking instructions on location

- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-1423
> [FD20-1423] Find-a-Doc Location's Modified Hours if 24/7

- assets/json/acf-json/group_uamswp_physicians.json
- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-499
> [FD20-499] Include whether a provider accepts new patients in top section

- templates/loops/expertise-card.php
- templates/loops/location-card.php
- templates/single-expertise.php
- templates/single-locations.php
https://uamsweb.atlassian.net/browse/FD20-388
This is ready for the next release.
> [FD20-388] Remove reference to Location/Area of Expertise parent when in list of children

- uamswp-find-a-doc.php
https://uamsweb.atlassian.net/browse/FD20-2341
> [FD20-2341] Set up constant for Find-a-Doc version

- templates/single-clinical-resource.php
- templates/single-condition.php
- templates/single-expertise.php
- templates/single-locations.php
- templates/single-physicians.php
- templates/single-treatment.php
https://uamsweb.atlassian.net/browse/FD20-466
This is ready for the next release.
> [FD20-466] Programmatically Add Keywords to Meta Titles

- templates/single-physicians.php
Based on https://transparency.nrchealth.com/documentation/widget
> Add Custom HTML for the paging controls for the comments list

- templates/blocks/clinical-resources.php
- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-2468
> [FD20-2468] Change Education heading to Education and Training on Provider Profile

- assets/json/acf-json/group_uamswp_hospital_affiliations.json
- includes/class.fad-gmb-settings-page.php
https://uamsweb.atlassian.net/browse/FD20-2606
* Added fields to Hospital Affiliation and used them in the Doximity CSV
* Fixed a bug with Doximity Address 2 by rebuilding Address 2 output.
* Replaced &amp; with & in constructed URLs, since this isn't outputting on a page anymore.
* Stripped phantom line breaks from excerpt string.
> [FD20-2606] Move GMB table to CSV Export

- gulpfile.js
- package.json
https://uamsweb.atlassian.net/browse/FD20-2474
> [FD20-2474] Evaluate and Update Versions for NPM Packages

- templates/single-physicians.php
Ready for next release.
https://uamsweb.atlassian.net/browse/FD20-397
> [FD20-397] Provider more reviews button href accessibility

- includes/class.fad-acf-functions.php
Ready for the next release.
https://uamsweb.atlassian.net/browse/FD20-411
> [FD20-411 v2] Set a child location's region from parent location's region

- templates/single-clinical-resource.php
- templates/single-condition.php
- templates/single-expertise.php
- templates/single-locations.php
- templates/single-physicians.php
- templates/single-treatment.php
Adding changes back that had been overwritten by https://github.com/UAMS-Web/UAMSWP-Find-a-Doc/commit/8055496a46a56b54dd78b54b74d06c00e4be6ff6
> [FD20-466 v2] Programmatically Add Keywords to Meta Titles

- includes/class.fad-custom-post.php
- includes/class.fad-gmb-settings-page.php
- uamswp-find-a-doc.php
https://uamsweb.atlassian.net/browse/FD20-3131
> [FD20-3131] Update GMB Export Columns

- templates/blocks/appointment-provider.php
- templates/blocks/clinical-resources.php
- templates/blocks/locations-phone.php
- templates/blocks/locations.php
- templates/blocks/providers.php
- templates/fwp/physician-loop.php
- templates/loops/expertise-card.php
- templates/loops/location-card.php
- templates/loops/physician-card.php
- templates/loops/resource-card.php
- templates/loops/resource-list-item.php
- templates/single-clinical-resource.php
- templates/single-condition.php
- templates/single-expertise.php
- templates/single-locations.php
- templates/single-physicians.php
- templates/single-treatment.php
https://uamsweb.atlassian.net/browse/FD20-2956
> [FD20-2956] add overwritten changes

- assets/json/acf-json/group_uamswp_conditions_cpt.json
- assets/json/acf-json/group_uamswp_treatments_cpt.json
- assets/json/old/group_uamswp_conditions.json
- assets/json/old/group_uamswp_treatments.json
- templates/loops/conditions-loop.php
- templates/loops/treatments-loop.php
- templates/single-condition.php
- templates/single-expertise.php
- templates/single-physicians.php
- templates/single-treatment.php
- templates/taxonomy-condition.php
- templates/taxonomy-treatment_procedure.php
This is ready for the next release.
https://uamsweb.atlassian.net/browse/FD20-3218
> [FD20-3218] Adjust Provider Language on Treatment Profile

- templates/loops/location-card.php
- templates/single-locations.php
- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-3244
> [FD20-3244] Add "the" in Find-a-Doc location subtitle

- includes/class.fad-gmb-settings-page.php
> Fd20 3131 update gmb export columns

- templates/blocks/locations-phone.php
https://uamsweb.atlassian.net/browse/FD20-3251
> [FD20-3251] PHP Error, Undefined variable: location_phone_numbers

- templates/blocks/locations-phone.php
> [FD20-3251] Establish empty variables

- assets/json/acf-json/group_uamswp_clinical_specialization.json
- assets/json/acf-json/group_uamswp_language.json
- assets/json/acf-json/group_uamswp_physicians.json
- assets/json/acf-json/group_uamswp_schema.json
- includes/class.fad-custom-post.php
- includes/class.fad-functions.php
- templates/fwp/physician-loop.php
- templates/loops/physician-card.php
- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-3873
> [FD20-3873] Small Fixes Related to FD20-3862

- includes/class.fad-custom-post.php
https://uamsweb.atlassian.net/browse/FD20-4025
I determined my actual mistake that caused this bug. It wasn't that I forgot to pass in a variable from outside. It was that I changed my mind about the name of a new variable inside the function after I'd already started using that variable without updating the existing instances of that variable.
> [FD20-4025] Bug - PHP Errors from Find-a-Doc plugin

- includes/class.fad-functions.php
- templates/single-physicians.php
> Fd20 4166 press ganey api integration for transparency

- includes/class.fad-functions.php
https://uamsweb.atlassian.net/browse/FD20-4191
> [FD20-4191] Find-a-Doc provider section's AJAX filter reset button has no accessible name

- templates/single-locations.php
- templates/single-physicians.php
https://uamsweb.atlassian.net/browse/FD20-4192
> [FD20-4192] Find-a-Doc map legend needs a defined role attribute to be permitted aria-label

- templates/loops/expertise-card.php
https://uamsweb.atlassian.net/browse/FD20-4193
> [FD20-4193] Area of Expertise card image link has no text (accessibility error)

- templates/fwp/physician-loop.php
https://uamsweb.atlassian.net/browse/FD20-4193
> [FD20-4193] Area of Expertise and Provider card image link has no text (accessibility error)
